import { type AppState } from './types'

export const initialAppState: AppState = {
  workspace: {
    company: 'LeadRescue Demo Co.',
    plan: 'Growth',
    responseTargetMinutes: 5,
    serviceAreas: ['Toronto', 'Mississauga', 'Oakville', 'Brampton', 'Etobicoke'],
    owners: ['Dispatch', 'Sales', 'Front desk', 'Ops'],
    defaultBookingType: 'Estimate or consultation',
  },
  leads: [
    {
      id: 'LR-1042',
      name: 'Maya Chen',
      business: 'Homeowner',
      industry: 'Roofing',
      source: 'Missed call',
      channel: 'Phone',
      arrived: '2 min ago',
      service: 'Emergency leak inspection',
      area: 'Mississauga',
      stage: 'Captured',
      value: 1800,
      urgency: 'High',
      owner: 'Dispatch',
      temperature: 94,
      nextAction: 'Request address and leak status',
      reply: 'Thanks for reaching out. Can you share the property address and whether there is active leaking right now?',
      tags: ['Storm lead', 'Needs address', 'Fast reply'],
      conversation: ['Missed call detected', 'Caller asked for same-day help', 'No address captured yet'],
      notes: ['Same-day urgency. Ask for address before booking.'],
    },
    {
      id: 'LR-1043',
      name: 'Dr. Singh',
      business: 'Clinic inquiry',
      industry: 'Clinics',
      source: 'Website form',
      channel: 'Form',
      arrived: '8 min ago',
      service: 'Appointment request',
      area: 'Toronto',
      stage: 'Qualified',
      value: 450,
      urgency: 'Medium',
      owner: 'Front desk',
      temperature: 78,
      nextAction: 'Offer callback windows',
      reply: 'We can help. Which service are you looking for, and do mornings or afternoons work better?',
      tags: ['New patient', 'Callback', 'Service unknown'],
      conversation: ['Form submitted', 'Asked for earliest available appointment', 'Phone number validated'],
      notes: ['Needs service type before booking.'],
    },
    {
      id: 'LR-1044',
      name: 'Rafael Ortiz',
      business: 'Renovation prospect',
      industry: 'Renovation',
      source: 'Instagram DM',
      channel: 'DM',
      arrived: '21 min ago',
      service: 'Kitchen remodel',
      area: 'Oakville',
      stage: 'Booked',
      value: 5200,
      urgency: 'Medium',
      owner: 'Sales',
      temperature: 84,
      nextAction: 'Confirm discovery call',
      reply: 'What space are you renovating, and what timeline are you hoping for?',
      tags: ['High value', 'Discovery booked', 'Design scope'],
      conversation: ['DM received', 'Budget range shared', 'Discovery slot held for tomorrow'],
      notes: ['Good fit for Premium workflow example.'],
    },
    {
      id: 'LR-1045',
      name: 'Amelia Brooks',
      business: 'Cleaning quote',
      industry: 'Cleaning',
      source: 'Quote form',
      channel: 'Form',
      arrived: '44 min ago',
      service: 'Recurring cleaning',
      area: 'Brampton',
      stage: 'Follow-up',
      value: 320,
      urgency: 'Low',
      owner: 'Ops',
      temperature: 61,
      nextAction: 'Send reminder 2',
      reply: 'Is this a one-time clean or recurring service, and how many rooms should we include?',
      tags: ['Price shopper', 'Reminder due', 'Recurring'],
      conversation: ['Quote form submitted', 'Touch 1 sent', 'No reply after 18 hours'],
      notes: ['Use value proof before discounting.'],
    },
    {
      id: 'LR-1046',
      name: 'Nadia Patel',
      business: 'HVAC homeowner',
      industry: 'HVAC',
      source: 'Google Ads form',
      channel: 'Ad',
      arrived: '1 hr ago',
      service: 'No heat call',
      area: 'Etobicoke',
      stage: 'Captured',
      value: 950,
      urgency: 'High',
      owner: 'Dispatch',
      temperature: 89,
      nextAction: 'Route to emergency queue',
      reply: 'Is this no heat right now, and is anyone vulnerable in the home? We can route this as priority if needed.',
      tags: ['Emergency', 'No heat', 'Priority'],
      conversation: ['Ad form captured', 'Selected no heat', 'Postal code inside service area'],
      notes: ['Emergency routing should be active.'],
    },
  ],
  automations: [
    {
      id: 'auto-missed-call',
      name: 'Missed call rescue',
      trigger: 'Phone lead arrives without answer',
      action: 'Create callback task, draft SMS, alert owner',
      status: 'Active',
      plan: 'Starter',
    },
    {
      id: 'auto-high-urgency',
      name: 'High urgency priority route',
      trigger: 'Urgency is High or heat is above 85',
      action: 'Pin to top of queue and assign Dispatch',
      status: 'Active',
      plan: 'Growth',
    },
    {
      id: 'auto-quote-followup',
      name: 'Quote follow-up',
      trigger: 'Qualified lead quiet for 18 hours',
      action: 'Start 5-touch reminder sequence',
      status: 'Active',
      plan: 'Growth',
    },
    {
      id: 'auto-review-request',
      name: 'Review request',
      trigger: 'Lead moves to Won',
      action: 'Schedule post-service review request',
      status: 'Paused',
      plan: 'Premium',
    },
  ],
  sequences: [
    {
      id: 'seq-new-lead',
      name: 'New lead confirmation',
      audience: 'Captured leads',
      status: 'Live',
      touches: ['Instant confirmation', 'Missing question', 'Booking window', 'Close loop'],
    },
    {
      id: 'seq-quote-nudge',
      name: 'Quote nudge',
      audience: 'Qualified quotes',
      status: 'Live',
      touches: ['Quote received', 'Proof touch', 'Two booking options', 'Final check-in'],
    },
    {
      id: 'seq-review',
      name: 'Review request',
      audience: 'Won customers',
      status: 'Draft',
      touches: ['Thank you', 'Review link', 'Referral ask'],
    },
  ],
  templates: [
    {
      id: 'tpl-roofing',
      industry: 'Roofing',
      goal: 'Book emergency estimates before the homeowner calls another provider.',
      questions: ['Property address', 'Active leak status', 'Damage photos', 'Preferred callback window'],
      reply: 'Can you share the property address and whether there is active leaking right now?',
      plan: 'Growth',
    },
    {
      id: 'tpl-clinic',
      industry: 'Clinics',
      goal: 'Route appointment requests to the correct callback path.',
      questions: ['Service type', 'Preferred location', 'Morning or afternoon', 'New or returning patient'],
      reply: 'Which service are you looking for, and do mornings or afternoons work better?',
      plan: 'Growth',
    },
    {
      id: 'tpl-renovation',
      industry: 'Renovation',
      goal: 'Qualify scope, budget, and timing before a consult.',
      questions: ['Room or project type', 'Timeline', 'Budget range', 'Decision maker'],
      reply: 'What space are you renovating, and what timeline are you hoping for?',
      plan: 'Premium',
    },
    {
      id: 'tpl-hvac',
      industry: 'HVAC',
      goal: 'Separate emergency requests from standard quote inquiries.',
      questions: ['No heat or no cooling', 'Equipment type', 'Postal code', 'Anyone vulnerable in home'],
      reply: 'Is this no heat or no cooling right now, or are you looking for a quote?',
      plan: 'Growth',
    },
  ],
  integrations: [
    {
      id: 'int-openai',
      name: 'OpenAI reply engine',
      category: 'AI',
      status: 'Needs credentials',
      purpose: 'Generate context-aware replies, qualification prompts, and handoff summaries.',
      nextStep: 'Add API key, model policy, tone rules, and human approval settings.',
      plan: 'Growth',
    },
    {
      id: 'int-sms',
      name: 'SMS provider',
      category: 'Messaging',
      status: 'Needs credentials',
      purpose: 'Send missed-call replies, quote nudges, booking reminders, and review requests.',
      nextStep: 'Connect Twilio or preferred SMS provider and verify sending numbers.',
      plan: 'Growth',
    },
    {
      id: 'int-email',
      name: 'Email channel',
      category: 'Messaging',
      status: 'Planned',
      purpose: 'Send longer form responses, consultation prep, and quote follow-up messages.',
      nextStep: 'Choose transactional email provider and sender domain.',
      plan: 'Starter',
    },
    {
      id: 'int-crm',
      name: 'CRM sync',
      category: 'CRM',
      status: 'Planned',
      purpose: 'Push qualified leads, stage changes, and notes into the operating CRM.',
      nextStep: 'Select HubSpot, GoHighLevel, Jobber, ServiceTitan, or custom webhook target.',
      plan: 'Premium',
    },
    {
      id: 'int-calendar',
      name: 'Calendar booking',
      category: 'Calendar',
      status: 'Planned',
      purpose: 'Offer callback, estimate, consult, and appointment windows from live calendars.',
      nextStep: 'Connect Google Calendar, Microsoft 365, or booking link provider.',
      plan: 'Growth',
    },
    {
      id: 'int-database',
      name: 'Production database',
      category: 'Data',
      status: 'Needs credentials',
      purpose: 'Persist workspaces, leads, events, rules, messages, users, and audit reports.',
      nextStep: 'Provision database, schema, row-level access rules, and migrations.',
      plan: 'Starter',
    },
    {
      id: 'int-auth',
      name: 'Authentication',
      category: 'Security',
      status: 'Needs credentials',
      purpose: 'Protect the app with login, workspace roles, sessions, and account recovery.',
      nextStep: 'Choose auth provider and define Owner, Manager, and Responder roles.',
      plan: 'Starter',
    },
  ],
}
